# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snowdrop.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snowdrop.proto',
  package='snowdrop',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0esnowdrop.proto\x12\x08snowdrop\"-\n\x0b\x45\x63hoRequest\x12\x0c\n\x04\x42ody\x18\x01 \x01(\t\x12\x10\n\x08IDNumber\x18\x02 \x01(\r\"\x1c\n\x0c\x45\x63hoResponse\x12\x0c\n\x04\x42ody\x18\x01 \x01(\t2A\n\x04\x45\x63ho\x12\x39\n\x06\x45\x63hoMe\x12\x15.snowdrop.EchoRequest\x1a\x16.snowdrop.EchoResponse\"\x00\x62\x06proto3'
)




_ECHOREQUEST = _descriptor.Descriptor(
  name='EchoRequest',
  full_name='snowdrop.EchoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Body', full_name='snowdrop.EchoRequest.Body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IDNumber', full_name='snowdrop.EchoRequest.IDNumber', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=73,
)


_ECHORESPONSE = _descriptor.Descriptor(
  name='EchoResponse',
  full_name='snowdrop.EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Body', full_name='snowdrop.EchoResponse.Body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['EchoRequest'] = _ECHOREQUEST
DESCRIPTOR.message_types_by_name['EchoResponse'] = _ECHORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUEST,
  '__module__' : 'snowdrop_pb2'
  # @@protoc_insertion_point(class_scope:snowdrop.EchoRequest)
  })
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'snowdrop_pb2'
  # @@protoc_insertion_point(class_scope:snowdrop.EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)



_ECHO = _descriptor.ServiceDescriptor(
  name='Echo',
  full_name='snowdrop.Echo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=105,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='EchoMe',
    full_name='snowdrop.Echo.EchoMe',
    index=0,
    containing_service=None,
    input_type=_ECHOREQUEST,
    output_type=_ECHORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHO)

DESCRIPTOR.services_by_name['Echo'] = _ECHO

# @@protoc_insertion_point(module_scope)
